// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: 16-grpc/proto/calculator.proto

package calcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int64                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file__16_grpc_proto_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file__16_grpc_proto_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file__16_grpc_proto_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *AddRequest) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file__16_grpc_proto_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file__16_grpc_proto_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file__16_grpc_proto_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type FibRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"` // hasilkan n bilangan Fibonacci pertama
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FibRequest) Reset() {
	*x = FibRequest{}
	mi := &file__16_grpc_proto_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FibRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibRequest) ProtoMessage() {}

func (x *FibRequest) ProtoReflect() protoreflect.Message {
	mi := &file__16_grpc_proto_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibRequest.ProtoReflect.Descriptor instead.
func (*FibRequest) Descriptor() ([]byte, []int) {
	return file__16_grpc_proto_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *FibRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type FibResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FibResponse) Reset() {
	*x = FibResponse{}
	mi := &file__16_grpc_proto_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FibResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibResponse) ProtoMessage() {}

func (x *FibResponse) ProtoReflect() protoreflect.Message {
	mi := &file__16_grpc_proto_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibResponse.ProtoReflect.Descriptor instead.
func (*FibResponse) Descriptor() ([]byte, []int) {
	return file__16_grpc_proto_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *FibResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File__16_grpc_proto_calculator_proto protoreflect.FileDescriptor

const file__16_grpc_proto_calculator_proto_rawDesc = "" +
	"\n" +
	"\x1e16-grpc/proto/calculator.proto\x12\n" +
	"calculator\"(\n" +
	"\n" +
	"AddRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x03R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x03R\x01b\"%\n" +
	"\vAddResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result\"\x1a\n" +
	"\n" +
	"FibRequest\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n\"#\n" +
	"\vFibResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value2\xc1\x01\n" +
	"\n" +
	"Calculator\x126\n" +
	"\x03Add\x12\x16.calculator.AddRequest\x1a\x17.calculator.AddResponse\x12;\n" +
	"\bMultiply\x12\x16.calculator.AddRequest\x1a\x17.calculator.AddResponse\x12>\n" +
	"\tFibonacci\x12\x16.calculator.FibRequest\x1a\x17.calculator.FibResponse0\x01B\"Z go-learning/16-grpc/proto;calcpbb\x06proto3"

var (
	file__16_grpc_proto_calculator_proto_rawDescOnce sync.Once
	file__16_grpc_proto_calculator_proto_rawDescData []byte
)

func file__16_grpc_proto_calculator_proto_rawDescGZIP() []byte {
	file__16_grpc_proto_calculator_proto_rawDescOnce.Do(func() {
		file__16_grpc_proto_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file__16_grpc_proto_calculator_proto_rawDesc), len(file__16_grpc_proto_calculator_proto_rawDesc)))
	})
	return file__16_grpc_proto_calculator_proto_rawDescData
}

var file__16_grpc_proto_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file__16_grpc_proto_calculator_proto_goTypes = []any{
	(*AddRequest)(nil),  // 0: calculator.AddRequest
	(*AddResponse)(nil), // 1: calculator.AddResponse
	(*FibRequest)(nil),  // 2: calculator.FibRequest
	(*FibResponse)(nil), // 3: calculator.FibResponse
}
var file__16_grpc_proto_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.Calculator.Add:input_type -> calculator.AddRequest
	0, // 1: calculator.Calculator.Multiply:input_type -> calculator.AddRequest
	2, // 2: calculator.Calculator.Fibonacci:input_type -> calculator.FibRequest
	1, // 3: calculator.Calculator.Add:output_type -> calculator.AddResponse
	1, // 4: calculator.Calculator.Multiply:output_type -> calculator.AddResponse
	3, // 5: calculator.Calculator.Fibonacci:output_type -> calculator.FibResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file__16_grpc_proto_calculator_proto_init() }
func file__16_grpc_proto_calculator_proto_init() {
	if File__16_grpc_proto_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file__16_grpc_proto_calculator_proto_rawDesc), len(file__16_grpc_proto_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file__16_grpc_proto_calculator_proto_goTypes,
		DependencyIndexes: file__16_grpc_proto_calculator_proto_depIdxs,
		MessageInfos:      file__16_grpc_proto_calculator_proto_msgTypes,
	}.Build()
	File__16_grpc_proto_calculator_proto = out.File
	file__16_grpc_proto_calculator_proto_goTypes = nil
	file__16_grpc_proto_calculator_proto_depIdxs = nil
}
