// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: 17-studi-kasus-microservices/proto/inventory.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductID) Reset() {
	*x = ProductID{}
	mi := &file__17_studi_kasus_microservices_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductID) ProtoMessage() {}

func (x *ProductID) ProtoReflect() protoreflect.Message {
	mi := &file__17_studi_kasus_microservices_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductID.ProtoReflect.Descriptor instead.
func (*ProductID) Descriptor() ([]byte, []int) {
	return file__17_studi_kasus_microservices_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *ProductID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Stock         int64                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file__17_studi_kasus_microservices_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file__17_studi_kasus_microservices_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file__17_studi_kasus_microservices_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Qty           int64                  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file__17_studi_kasus_microservices_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file__17_studi_kasus_microservices_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file__17_studi_kasus_microservices_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReserveRequest) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type ReserveResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ok             bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	RemainingStock int64                  `protobuf:"varint,2,opt,name=remaining_stock,json=remainingStock,proto3" json:"remaining_stock,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveResponse) Reset() {
	*x = ReserveResponse{}
	mi := &file__17_studi_kasus_microservices_proto_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveResponse) ProtoMessage() {}

func (x *ReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file__17_studi_kasus_microservices_proto_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveResponse.ProtoReflect.Descriptor instead.
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return file__17_studi_kasus_microservices_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReserveResponse) GetRemainingStock() int64 {
	if x != nil {
		return x.RemainingStock
	}
	return 0
}

var File__17_studi_kasus_microservices_proto_inventory_proto protoreflect.FileDescriptor

const file__17_studi_kasus_microservices_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"217-studi-kasus-microservices/proto/inventory.proto\x12\tinventory\"\x1b\n" +
	"\tProductID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Y\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x03R\x05stock\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\"A\n" +
	"\x0eReserveRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\x03R\x03qty\"J\n" +
	"\x0fReserveResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12'\n" +
	"\x0fremaining_stock\x18\x02 \x01(\x03R\x0eremainingStock2\x8a\x01\n" +
	"\tInventory\x126\n" +
	"\n" +
	"GetProduct\x12\x14.inventory.ProductID\x1a\x12.inventory.Product\x12E\n" +
	"\fReserveStock\x12\x19.inventory.ReserveRequest\x1a\x1a.inventory.ReserveResponseB<Z:go-learning/17-studi-kasus-microservices/proto;inventorypbb\x06proto3"

var (
	file__17_studi_kasus_microservices_proto_inventory_proto_rawDescOnce sync.Once
	file__17_studi_kasus_microservices_proto_inventory_proto_rawDescData []byte
)

func file__17_studi_kasus_microservices_proto_inventory_proto_rawDescGZIP() []byte {
	file__17_studi_kasus_microservices_proto_inventory_proto_rawDescOnce.Do(func() {
		file__17_studi_kasus_microservices_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file__17_studi_kasus_microservices_proto_inventory_proto_rawDesc), len(file__17_studi_kasus_microservices_proto_inventory_proto_rawDesc)))
	})
	return file__17_studi_kasus_microservices_proto_inventory_proto_rawDescData
}

var file__17_studi_kasus_microservices_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file__17_studi_kasus_microservices_proto_inventory_proto_goTypes = []any{
	(*ProductID)(nil),       // 0: inventory.ProductID
	(*Product)(nil),         // 1: inventory.Product
	(*ReserveRequest)(nil),  // 2: inventory.ReserveRequest
	(*ReserveResponse)(nil), // 3: inventory.ReserveResponse
}
var file__17_studi_kasus_microservices_proto_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.Inventory.GetProduct:input_type -> inventory.ProductID
	2, // 1: inventory.Inventory.ReserveStock:input_type -> inventory.ReserveRequest
	1, // 2: inventory.Inventory.GetProduct:output_type -> inventory.Product
	3, // 3: inventory.Inventory.ReserveStock:output_type -> inventory.ReserveResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file__17_studi_kasus_microservices_proto_inventory_proto_init() }
func file__17_studi_kasus_microservices_proto_inventory_proto_init() {
	if File__17_studi_kasus_microservices_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file__17_studi_kasus_microservices_proto_inventory_proto_rawDesc), len(file__17_studi_kasus_microservices_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file__17_studi_kasus_microservices_proto_inventory_proto_goTypes,
		DependencyIndexes: file__17_studi_kasus_microservices_proto_inventory_proto_depIdxs,
		MessageInfos:      file__17_studi_kasus_microservices_proto_inventory_proto_msgTypes,
	}.Build()
	File__17_studi_kasus_microservices_proto_inventory_proto = out.File
	file__17_studi_kasus_microservices_proto_inventory_proto_goTypes = nil
	file__17_studi_kasus_microservices_proto_inventory_proto_depIdxs = nil
}
