// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: 34-grpc-advanced/proto/math.proto

package mathpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Math_Sum_FullMethodName       = "/math.Math/Sum"
	Math_Echo_FullMethodName      = "/math.Math/Echo"
	Math_SlowUnary_FullMethodName = "/math.Math/SlowUnary"
)

// MathClient is the client API for Math service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MathClient interface {
	// Client streaming: client kirim BANYAK angka -> server balas SATU total.
	Sum(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NumberRequest, SumResponse], error)
	// Bidirectional streaming: client & server saling kirim aliran pesan.
	Echo(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoMessage, EchoMessage], error)
	// Unary yang menghormati deadline (untuk demo timeout/cancellation).
	SlowUnary(ctx context.Context, in *SlowRequest, opts ...grpc.CallOption) (*SlowResponse, error)
}

type mathClient struct {
	cc grpc.ClientConnInterface
}

func NewMathClient(cc grpc.ClientConnInterface) MathClient {
	return &mathClient{cc}
}

func (c *mathClient) Sum(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NumberRequest, SumResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Math_ServiceDesc.Streams[0], Math_Sum_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NumberRequest, SumResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Math_SumClient = grpc.ClientStreamingClient[NumberRequest, SumResponse]

func (c *mathClient) Echo(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoMessage, EchoMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Math_ServiceDesc.Streams[1], Math_Echo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EchoMessage, EchoMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Math_EchoClient = grpc.BidiStreamingClient[EchoMessage, EchoMessage]

func (c *mathClient) SlowUnary(ctx context.Context, in *SlowRequest, opts ...grpc.CallOption) (*SlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SlowResponse)
	err := c.cc.Invoke(ctx, Math_SlowUnary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MathServer is the server API for Math service.
// All implementations must embed UnimplementedMathServer
// for forward compatibility.
type MathServer interface {
	// Client streaming: client kirim BANYAK angka -> server balas SATU total.
	Sum(grpc.ClientStreamingServer[NumberRequest, SumResponse]) error
	// Bidirectional streaming: client & server saling kirim aliran pesan.
	Echo(grpc.BidiStreamingServer[EchoMessage, EchoMessage]) error
	// Unary yang menghormati deadline (untuk demo timeout/cancellation).
	SlowUnary(context.Context, *SlowRequest) (*SlowResponse, error)
	mustEmbedUnimplementedMathServer()
}

// UnimplementedMathServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMathServer struct{}

func (UnimplementedMathServer) Sum(grpc.ClientStreamingServer[NumberRequest, SumResponse]) error {
	return status.Error(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedMathServer) Echo(grpc.BidiStreamingServer[EchoMessage, EchoMessage]) error {
	return status.Error(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedMathServer) SlowUnary(context.Context, *SlowRequest) (*SlowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SlowUnary not implemented")
}
func (UnimplementedMathServer) mustEmbedUnimplementedMathServer() {}
func (UnimplementedMathServer) testEmbeddedByValue()              {}

// UnsafeMathServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MathServer will
// result in compilation errors.
type UnsafeMathServer interface {
	mustEmbedUnimplementedMathServer()
}

func RegisterMathServer(s grpc.ServiceRegistrar, srv MathServer) {
	// If the following call panics, it indicates UnimplementedMathServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Math_ServiceDesc, srv)
}

func _Math_Sum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MathServer).Sum(&grpc.GenericServerStream[NumberRequest, SumResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Math_SumServer = grpc.ClientStreamingServer[NumberRequest, SumResponse]

func _Math_Echo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MathServer).Echo(&grpc.GenericServerStream[EchoMessage, EchoMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Math_EchoServer = grpc.BidiStreamingServer[EchoMessage, EchoMessage]

func _Math_SlowUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServer).SlowUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Math_SlowUnary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServer).SlowUnary(ctx, req.(*SlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Math_ServiceDesc is the grpc.ServiceDesc for Math service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Math_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "math.Math",
	HandlerType: (*MathServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SlowUnary",
			Handler:    _Math_SlowUnary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sum",
			Handler:       _Math_Sum_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Echo",
			Handler:       _Math_Echo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "34-grpc-advanced/proto/math.proto",
}
