// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: 34-grpc-advanced/proto/math.proto

package mathpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberRequest) Reset() {
	*x = NumberRequest{}
	mi := &file__34_grpc_advanced_proto_math_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberRequest) ProtoMessage() {}

func (x *NumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file__34_grpc_advanced_proto_math_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberRequest.ProtoReflect.Descriptor instead.
func (*NumberRequest) Descriptor() ([]byte, []int) {
	return file__34_grpc_advanced_proto_math_proto_rawDescGZIP(), []int{0}
}

func (x *NumberRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sum           int64                  `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumResponse) Reset() {
	*x = SumResponse{}
	mi := &file__34_grpc_advanced_proto_math_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumResponse) ProtoMessage() {}

func (x *SumResponse) ProtoReflect() protoreflect.Message {
	mi := &file__34_grpc_advanced_proto_math_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumResponse.ProtoReflect.Descriptor instead.
func (*SumResponse) Descriptor() ([]byte, []int) {
	return file__34_grpc_advanced_proto_math_proto_rawDescGZIP(), []int{1}
}

func (x *SumResponse) GetSum() int64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type EchoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoMessage) Reset() {
	*x = EchoMessage{}
	mi := &file__34_grpc_advanced_proto_math_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoMessage) ProtoMessage() {}

func (x *EchoMessage) ProtoReflect() protoreflect.Message {
	mi := &file__34_grpc_advanced_proto_math_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoMessage.ProtoReflect.Descriptor instead.
func (*EchoMessage) Descriptor() ([]byte, []int) {
	return file__34_grpc_advanced_proto_math_proto_rawDescGZIP(), []int{2}
}

func (x *EchoMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelayMs       int32                  `protobuf:"varint,1,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlowRequest) Reset() {
	*x = SlowRequest{}
	mi := &file__34_grpc_advanced_proto_math_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowRequest) ProtoMessage() {}

func (x *SlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file__34_grpc_advanced_proto_math_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowRequest.ProtoReflect.Descriptor instead.
func (*SlowRequest) Descriptor() ([]byte, []int) {
	return file__34_grpc_advanced_proto_math_proto_rawDescGZIP(), []int{3}
}

func (x *SlowRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type SlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlowResponse) Reset() {
	*x = SlowResponse{}
	mi := &file__34_grpc_advanced_proto_math_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowResponse) ProtoMessage() {}

func (x *SlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file__34_grpc_advanced_proto_math_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowResponse.ProtoReflect.Descriptor instead.
func (*SlowResponse) Descriptor() ([]byte, []int) {
	return file__34_grpc_advanced_proto_math_proto_rawDescGZIP(), []int{4}
}

func (x *SlowResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File__34_grpc_advanced_proto_math_proto protoreflect.FileDescriptor

const file__34_grpc_advanced_proto_math_proto_rawDesc = "" +
	"\n" +
	"!34-grpc-advanced/proto/math.proto\x12\x04math\"%\n" +
	"\rNumberRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"\x1f\n" +
	"\vSumResponse\x12\x10\n" +
	"\x03sum\x18\x01 \x01(\x03R\x03sum\"!\n" +
	"\vEchoMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"(\n" +
	"\vSlowRequest\x12\x19\n" +
	"\bdelay_ms\x18\x01 \x01(\x05R\adelayMs\"&\n" +
	"\fSlowResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\x9d\x01\n" +
	"\x04Math\x12/\n" +
	"\x03Sum\x12\x13.math.NumberRequest\x1a\x11.math.SumResponse(\x01\x120\n" +
	"\x04Echo\x12\x11.math.EchoMessage\x1a\x11.math.EchoMessage(\x010\x01\x122\n" +
	"\tSlowUnary\x12\x11.math.SlowRequest\x1a\x12.math.SlowResponseB+Z)go-learning/34-grpc-advanced/proto;mathpbb\x06proto3"

var (
	file__34_grpc_advanced_proto_math_proto_rawDescOnce sync.Once
	file__34_grpc_advanced_proto_math_proto_rawDescData []byte
)

func file__34_grpc_advanced_proto_math_proto_rawDescGZIP() []byte {
	file__34_grpc_advanced_proto_math_proto_rawDescOnce.Do(func() {
		file__34_grpc_advanced_proto_math_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file__34_grpc_advanced_proto_math_proto_rawDesc), len(file__34_grpc_advanced_proto_math_proto_rawDesc)))
	})
	return file__34_grpc_advanced_proto_math_proto_rawDescData
}

var file__34_grpc_advanced_proto_math_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file__34_grpc_advanced_proto_math_proto_goTypes = []any{
	(*NumberRequest)(nil), // 0: math.NumberRequest
	(*SumResponse)(nil),   // 1: math.SumResponse
	(*EchoMessage)(nil),   // 2: math.EchoMessage
	(*SlowRequest)(nil),   // 3: math.SlowRequest
	(*SlowResponse)(nil),  // 4: math.SlowResponse
}
var file__34_grpc_advanced_proto_math_proto_depIdxs = []int32{
	0, // 0: math.Math.Sum:input_type -> math.NumberRequest
	2, // 1: math.Math.Echo:input_type -> math.EchoMessage
	3, // 2: math.Math.SlowUnary:input_type -> math.SlowRequest
	1, // 3: math.Math.Sum:output_type -> math.SumResponse
	2, // 4: math.Math.Echo:output_type -> math.EchoMessage
	4, // 5: math.Math.SlowUnary:output_type -> math.SlowResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file__34_grpc_advanced_proto_math_proto_init() }
func file__34_grpc_advanced_proto_math_proto_init() {
	if File__34_grpc_advanced_proto_math_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file__34_grpc_advanced_proto_math_proto_rawDesc), len(file__34_grpc_advanced_proto_math_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file__34_grpc_advanced_proto_math_proto_goTypes,
		DependencyIndexes: file__34_grpc_advanced_proto_math_proto_depIdxs,
		MessageInfos:      file__34_grpc_advanced_proto_math_proto_msgTypes,
	}.Build()
	File__34_grpc_advanced_proto_math_proto = out.File
	file__34_grpc_advanced_proto_math_proto_goTypes = nil
	file__34_grpc_advanced_proto_math_proto_depIdxs = nil
}
