apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-goapp
spec:
  replicas: {{ .Values.replicaCount }}   # nilai dari values.yaml
  selector:
    matchLabels:
      app: {{ .Release.Name }}-goapp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-goapp
    spec:
      containers:
        - name: goapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: PORT
              value: "{{ .Values.env.PORT }}"
          livenessProbe:
            httpGet: { path: /healthz, port: {{ .Values.service.targetPort }} }
          readinessProbe:
            httpGet: { path: /readyz, port: {{ .Values.service.targetPort }} }
          resources:
{{ toYaml .Values.resources | indent 12 }}
